### ISSUE TITLE
TextArea has a problem

### ISSUE THREAD

**Issue by leo12wb** [govapps/mtw-nuxt-components#1]
localizado em "components/TextArea.vue" apresenta em seu conteúdo a falta de uma importação. segue abaixo o codigo em falta
```html
...
<script lang="ts" setup>
    import { ref, onMounted } from "vue";
 ...
```

**Comment by juliolimareis** [comment]
@leo12wb Reamente falta esse ajuste. Porém esse componente está `deprecated`.

Solução: Para se usar Text é será via Input: Passando o parâmetro `variant="textarea"`.  Assim transformando o input em text-area e herdando todas suas funcionalidades programadas. 

https://github.com/govapps/mtw-nuxt-components/blob/c5a04a272988334f0afcaad66eac2b58ae28374b/components/Input.vue#L5
