### ISSUE TITLE
Input causando aviso no chrome

### ISSUE THREAD

**Issue by YasCoMa** [govapps/mtw-nuxt-components#3]
Usando a versão atualizada de Input do company funciona e valida corretamente.
Porém no chrome ele gera o seguinte aviso:
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom.

**Comment by juliolimareis** [comment]
Olá @YasCoMa precisamos econtrar a causa disso. Se encontrar a solução pode enviar o PR para `develop`

**Comment by YasCoMa** [comment]
As duas dão este warning, a diferença é que pelo menos a versão do Input dá para testar a funcionalidade que preciso do formulário. Já a versão Input daqui do repositório o input não valida e não faz as modificações necessárias.

**Comment by YasCoMa** [comment]
A solução é colocar a parte do <component ... /> dentro de <ClientOnly> </ClientOnly>.
Eu mandar a pull request, mas seria em cima da que eu enviei antes, pois a daqui não funciona a validação e as mensagens helper pro usuário que não aparecem.
