### ISSUE TITLE
Sugestão de tipagem component Dialog

### ISSUE THREAD

**Issue by SrAlbuquerque** [govapps/mtw-nuxt-components#5]
poderia colocar a tipagem no parâmetro do componente Dialog

**Comment by YasCoMa** [comment]
Mas todas as propriedades estão com seus tipos definidos no Dialog.

**Comment by juliolimareis** [comment]
As tipagem default do vue não são suficientes para nos fornecer mais detalhes.

Solução: Trocar para TS. Isso vai virar um fix em breve para @SrAlbuquerque 

Parecido com o que foi feito no Input:

https://github.com/govapps/mtw-nuxt-components/blob/c5a04a272988334f0afcaad66eac2b58ae28374b/components/Input.vue#L80

**Comment by YasCoMa** [comment]
Eu padronizei no novo formato as props do Dialog para ti já mandei na fila junto com as outras modificações do select na minha última PR. Fiz o mesmo para o select.

**Comment by juliolimareis** [comment]
Desenvolvido. https://github.com/govapps/mtw-nuxt-components/pull/7

**Comment by juliolimareis** [comment]
Resolvido no PR https://github.com/govapps/mtw-nuxt-components/pull/7
